const categories = {
  '餐饮': { color: '#d69a3b', words: ['餐饮','餐厅','饭店','饭馆','小吃','快餐','家常菜','山东煎饼','煎饼','烧烤','火锅','麻辣烫','面馆','拉面','米线','盖饭','早餐加盟','早餐','午餐','晚餐','夜宵','外卖','美团','饿了么','肯德基','麦当劳','汉堡王','必胜客','德克士','咖啡','星巴克','瑞幸','库迪','幸运咖','奶茶','茶百道','蜜雪冰城','喜茶','奈雪','霸王茶姬','古茗','沪上阿姨','鲜果','水果店','蛋糕','面包','烘焙','零食','卤味','鸭脖','海底捞','西贝','兰州牛肉面'] },
  '交通': { color: '#0d8069', words: ['交通','中铁','滴滴','高德打车','曹操出行','T3出行','哈啰','花小猪','出租车','网约车','打车','地铁','公交','乘车码','高铁','火车票','铁路','机票','航空','航旅','携程','飞猪','租车','共享单车','青桔','加油','中石化','中石油','充电桩','停车','ETC','过路费'] },
  '购物': { color: '#4d81b8', words: ['购物','拼多多','拼夕夕','淘宝','天猫','京东','京喜','唯品会','抖音商城','快手小店','小红书','得物','闲鱼','转转','亚马逊','盒马','山姆','沃尔玛','永辉','大润发','超市','便利店','全家','罗森','7-eleven','名创优品','屈臣氏','优衣库','ZARA','HM','无印良品','宜家','服饰','服装','鞋店','数码','手机配件','日用品','母婴'] },
  '生活': { color: '#8269af', words: ['生活缴费','电费','水费','燃气','煤气','物业','房租','宽带','网费','话费','通信','移动','联通','电信','缴费','药店','医院','诊所','挂号','体检','医保','保险','理发','洗衣','家政','维修','快递','顺丰','菜鸟','打印','宠物','鲜花'] },
  '娱乐': { color: '#dd6657', words: ['娱乐','健身','健身房','健身卡','私教','瑜伽','普拉提','游泳','羽毛球','篮球','足球','乒乓球','桌球','攀岩','滑雪','跑步','运动馆','球馆','电影','影院','万达影城','猫眼','淘票票','游戏','Steam','网易游戏','腾讯游戏','王者荣耀','音乐','网易云音乐','QQ音乐','演出','演唱会','话剧','展览','博物馆','KTV','酒吧','桌游','会员','视频会员','爱奇艺','腾讯视频','优酷','哔哩哔哩'] },
  '其他': { color: '#82939b', words: [] }
};
const initialRecords = [];
let records = JSON.parse(localStorage.getItem('qingi-records') || 'null') || initialRecords;
function beijingDate(){const parts=new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const values=Object.fromEntries(parts.filter(part=>part.type!=='literal').map(part=>[part.type,Number(part.value)]));return new Date(values.year,values.month-1,values.day,12);}
let period = 'day'; let today = beijingDate(); let selectedDate = new Date(today); let budget = Number(localStorage.getItem('qingi-monthly-budget')) || 4500;
const $ = s => document.querySelector(s); const money = n => `¥ ${Math.abs(n).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
function classify(text) { const value = text.toLowerCase(); return Object.keys(categories).find(key => categories[key].words.some(word => value.includes(word.toLowerCase()))) || '其他'; }
function toDateKey(date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;}
function monthKey(date=selectedDate){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}`;}
function weekStart(date){const start=new Date(date);start.setDate(date.getDate()-(date.getDay()+6)%7);return start;}
function datesForPeriod(){if(period==='month')return[];if(period==='day')return[toDateKey(selectedDate)];const start=weekStart(selectedDate);return Array.from({length:7},(_,index)=>{const date=new Date(start);date.setDate(start.getDate()+index);return toDateKey(date);});}
function periodRecords(){if(period==='month')return records.filter(record=>record.date.startsWith(monthKey()));const dates=datesForPeriod();return records.filter(record=>dates.includes(record.date));}
function renderMetrics(list){const expense=list.filter(r=>r.amount<0).reduce((a,r)=>a+Math.abs(r.amount),0);const income=list.filter(r=>r.amount>0).reduce((a,r)=>a+r.amount,0);$('#expenseTotal').textContent=money(expense);$('#incomeTotal').textContent=money(income);$('#balanceTotal').textContent=money(income-expense);const allMonth=records.filter(record=>record.date.startsWith(monthKey())&&record.amount<0).reduce((a,record)=>a+Math.abs(record.amount),0);const pct=Math.min(100,Math.round(allMonth/budget*100));$('#budgetRemaining').textContent=money(Math.max(0,budget-allMonth));$('#budgetPercent').textContent=`${pct}%`;$('#budgetHint').textContent=`已使用 ${money(allMonth)} / ${money(budget)}`;$('.budget-ring').style.background=`conic-gradient(var(--gold) ${pct*3.6}deg,#eef0ed 0deg)`;$('#expenseCompare').textContent=list.length ? `${list.filter(r=>r.amount<0).length} 笔支出` : '本期暂无支出';}
function chartDates(){if(period==='day')return[new Date(selectedDate)];if(period==='week')return Array.from({length:7},(_,index)=>{const date=weekStart(selectedDate);date.setDate(date.getDate()+index);return date;});const days=new Date(selectedDate.getFullYear(),selectedDate.getMonth()+1,0).getDate();return Array.from({length:days},(_,index)=>new Date(selectedDate.getFullYear(),selectedDate.getMonth(),index+1));}
function renderChart(){const dates=chartDates();const values=dates.map(date=>records.filter(record=>record.date===toDateKey(date)&&record.amount<0).reduce((sum,record)=>sum+Math.abs(record.amount),0));const max=Math.max(...values,1);$('#trendChart').innerHTML=values.map((value,index)=>{const date=dates[index];const showLabel=dates.length<12||index===0||index===dates.length-1||date.getDate()%5===0;return `<div class="bar-wrap"><div class="bar ${toDateKey(date)===toDateKey(selectedDate)?'today':''}" style="height:${Math.max(2,value/max*100)}%"><span class="bar-label">${showLabel?`${date.getDate()}日`:''}</span></div></div>`;}).join('');}
function renderCategories(list){const totals={};list.filter(r=>r.amount<0).forEach(r=>totals[r.category]=(totals[r.category]||0)+Math.abs(r.amount));const items=Object.entries(totals).sort((a,b)=>b[1]-a[1]);const total=items.reduce((s,[,v])=>s+v,0);$('#donutAmount').textContent=total?`¥${Math.round(total)}`:'¥0';let position=0;const gradient=items.length?items.map(([name,value])=>{const start=position;position+=value/total*100;return `${categories[name].color} ${start}% ${position}%`;}).join(','):'#e8eeeb 0 100%';$('#donut').style.background=`conic-gradient(${gradient})`;$('#categoryList').innerHTML=items.length?items.slice(0,4).map(([name,value])=>`<div class="category-item"><i class="category-dot" style="background:${categories[name].color}"></i><span class="category-name">${name}</span><span class="category-value">${Math.round(value/total*100)}% &nbsp; ¥${value.toFixed(0)}</span></div>`).join(''):'<span class="comparison neutral">暂无支出分类</span>';}
function renderRecords(){const term=$('#searchInput').value.trim().toLowerCase(), filter=$('#categoryFilter').value, sort=$('#sortRecords').value;let list=periodRecords().filter(r=>(filter==='all'||r.category===filter)&&`${r.merchant} ${r.note}`.toLowerCase().includes(term));list.sort(sort==='amount-desc'?(a,b)=>Math.abs(b.amount)-Math.abs(a.amount)||b.date.localeCompare(a.date):(a,b)=>b.date.localeCompare(a.date)||b.id-a.id);$('#recordsBody').innerHTML=list.map(r=>`<tr><td>${r.date.slice(5).replace('-',' 月 ')} 日</td><td><span class="merchant">${r.merchant}</span><span class="subtext">${r.note||''}</span></td><td><span class="pill">${r.category}</span></td><td>${r.account}</td><td class="amount ${r.amount<0?'expense':'income'}">${r.amount<0?'-':'+'} ${money(r.amount)}</td><td><button class="delete-record" data-id="${r.id}" title="删除记录" aria-label="删除 ${r.merchant}">×</button></td></tr>`).join('');$('#emptyState').hidden=!!list.length;document.querySelectorAll('.delete-record').forEach(b=>b.onclick=()=>{records=records.filter(r=>r.id!==Number(b.dataset.id));save();render();toast('记录已删除');});}
function renderFilters(){const old=$('#categoryFilter').value;$('#categoryFilter').innerHTML='<option value="all">全部分类</option>'+Object.keys(categories).map(c=>`<option value="${c}">${c}</option>`).join('');$('#categoryFilter').value=old;}
function render(){const list=periodRecords();renderMetrics(list);renderChart();renderCategories(list);renderFilters();renderRecords();$('#dateQuery').value=toDateKey(selectedDate);$('#dateQuery').max=toDateKey(today);$('#periodLabel').textContent=`${selectedDate.getFullYear()} 年 ${selectedDate.getMonth()+1} 月`;$('#currentDate').textContent=`${selectedDate.getFullYear()} 年 ${selectedDate.getMonth()+1} 月 ${selectedDate.getDate()} 日`;$('#nextMonth').disabled=monthKey()===monthKey(today);}
function syncBeijingDate(){const current=beijingDate();if(toDateKey(current)===toDateKey(today))return;const wasToday=toDateKey(selectedDate)===toDateKey(today);today=current;if(wasToday)selectedDate=new Date(today);render();}
setInterval(syncBeijingDate,60000);
function save(){localStorage.setItem('qingi-records',JSON.stringify(records));}
function changeMonth(offset){const day=selectedDate.getDate();const target=new Date(selectedDate.getFullYear(),selectedDate.getMonth()+offset,1);target.setDate(Math.min(day,new Date(target.getFullYear(),target.getMonth()+1,0).getDate()));if(target>today)return;selectedDate=target;period='month';document.querySelectorAll('.period').forEach(button=>button.classList.toggle('active',button.dataset.period==='month'));render();}
$('#previousMonth').onclick=()=>changeMonth(-1);$('#nextMonth').onclick=()=>changeMonth(1);
$('#dateQuery').onchange=e=>{const date=new Date(`${e.target.value}T12:00:00`);if(Number.isNaN(date.getTime())||date>today)return;selectedDate=date;render();};
function saveBudget(){localStorage.setItem('qingi-monthly-budget',String(budget));}
$('#clearAllRecords').onclick=()=>{if(!records.length){toast('账单已经是空的');return;}if(!window.confirm(`确认清空全部 ${records.length} 笔账单记录吗？此操作无法撤销。`))return;records=[];save();render();toast('全部账单记录已清空');};
function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2500)}
$('#editBudget').onclick=()=>{const input=$('#budgetForm input[name="budget"]');input.value=budget;$('#budgetDialog').showModal();input.focus();input.select();};
$('#budgetForm').onsubmit=e=>{e.preventDefault();const value=Number(new FormData(e.target).get('budget'));if(!Number.isFinite(value)||value<=0){toast('请输入大于 0 的预算金额');return;}budget=value;saveBudget();$('#budgetDialog').close();render();toast('本月预算已更新');};
document.querySelector('a[href="#budgets"]').onclick=e=>{e.preventDefault();$('#editBudget').click();};
function rowsToRecords(rows,source){const headerIndex=rows.findIndex(row=>row.some(cell=>/交易时间|交易对方|收支金额|金额/.test(String(cell))));if(headerIndex<0)return[];const header=rows[headerIndex].map(value=>String(value).trim());return rows.slice(headerIndex+1).map((row,index)=>{const find=words=>{const column=header.findIndex(name=>words.some(word=>name.includes(word)));return column<0?'':String(row[column]??'').trim()};const merchant=find(['交易对方','商户','商家','名称'])||'导入账单';const detail=[find(['商品','商品说明','商品名称']),find(['备注','附言','说明'])].filter(Boolean).join(' ');const raw=find(['收支金额','金额'])||'0';const amount=Number(raw.replace(/[¥￥,\s]/g,''));const direction=find(['收/支','收支']);const transactionType=find(['交易类型']);const signal=`${merchant} ${detail} ${direction} ${transactionType}`;const transferToMoneyFund=/转入零钱通|存入零钱通|转入零钱通账户/.test(signal);const transferFromMoneyFund=/(从|由)?零钱通(账户)?(转入|转出|提现|取出)/.test(signal)||/从零钱通/.test(signal);const isExpense=transferToMoneyFund||/支出|付款|消费|扣款/.test(signal);const isIncome=transferFromMoneyFund||/收入|入账|收款|红包|退款/.test(signal);const income=isExpense?false:isIncome?true:amount>0;const date=(find(['交易时间','日期','时间'])||'2026-09-10').replace(/\//g,'-').slice(0,10);return {id:Date.now()+index,date,merchant,note:detail||`${source}导入`,category:classify(`${merchant} ${detail}`),account:source,amount:income?Math.abs(amount):-Math.abs(amount)};}).filter(record=>Number.isFinite(record.amount)&&record.amount!==0);}
function parseCSV(text,source){const rows=text.trim().split(/\r?\n/).map(line=>line.split(/,|\t/).map(cell=>cell.trim().replace(/^"|"$/g,'')));return rowsToRecords(rows,source);}
function parseSpreadsheet(buffer,source){if(!window.XLSX)throw new Error('Excel 解析组件未加载');const workbook=XLSX.read(buffer,{type:'array',cellDates:true});const sheet=workbook.Sheets[workbook.SheetNames[0]];return rowsToRecords(XLSX.utils.sheet_to_json(sheet,{header:1,defval:'',raw:false}),source);}
$('.import-button').onclick=()=>$('#importDialog').showModal();$('#wechatImport').onclick=()=>{$('#importDialog').close();$('#fileInput').dataset.source='微信支付';$('#fileInput').click()};$('#bankImport').onclick=()=>{$('#importDialog').close();$('#fileInput').dataset.source='银行卡';$('#fileInput').click()};$('#fileInput').onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const source=e.target.dataset.source||'账单';const added=/\.xlsx?$/i.test(file.name)?parseSpreadsheet(reader.result,source):parseCSV(reader.result,source);if(added.length){records=[...added,...records];save();render();toast(`已导入 ${added.length} 笔记录，并完成自动分类`)}else toast('未识别到账单记录，请检查表头或金额列')}catch(error){toast('导入失败，请确认文件是有效的 CSV 或 XLSX 账单')}finally{e.target.value=''}};if(/\.xlsx?$/i.test(file.name))reader.readAsArrayBuffer(file);else reader.readAsText(file,'utf-8')};
document.querySelectorAll('.period').forEach(b=>b.onclick=()=>{period=b.dataset.period;document.querySelectorAll('.period').forEach(x=>x.classList.toggle('active',x===b));render();});$('#searchInput').oninput=renderRecords;$('#categoryFilter').onchange=renderRecords;$('#sortRecords').onchange=renderRecords;$('#themeToggle').onclick=()=>document.body.classList.toggle('dark');$('#addRecord').onclick=()=>{const dateInput=$('#recordForm input[name="date"]');dateInput.value=toDateKey(selectedDate);$('#recordDialog').showModal();};document.querySelectorAll('.close-button,.cancel-button').forEach(button=>button.onclick=e=>{e.preventDefault();button.closest('dialog').close();});$('#recordForm').onsubmit=e=>{e.preventDefault();const d=new FormData(e.target);const merchant=d.get('merchant');const type=d.get('type');records.unshift({id:Date.now(),date:d.get('date'),merchant,note:'手动添加',category:d.get('category')==='auto'?classify(merchant):d.get('category'),account:d.get('account'),amount:(type==='income'?1:-1)*Number(d.get('amount'))});save();$('#recordDialog').close();e.target.reset();render();toast('记录已保存')};$('#manageCategories').onclick=()=>toast('分类管理将在下一版本提供');$('#showAllCategories').onclick=()=>{period='month';document.querySelectorAll('.period').forEach(x=>x.classList.toggle('active',x.dataset.period==='month'));render();location.hash='transactions'};Object.keys(categories).filter(c=>c!=='其他').forEach(c=>$('#formCategory').insertAdjacentHTML('beforeend',`<option value="${c}">${c}</option>`));render();
